repos:
  - repo: local
    hooks:
      - id: stylua
        name: StyLua
        language: system
        entry: stylua
        args: [--respect-ignores]
        types: [lua]
      - id: gendoc
        name: Gendoc
        language: system
        entry: make --silent doc
        types: [lua]
      - id: lintdoc
        name: LintDoc
        language: system
        entry: make --silent lintdoc
        types: [lua]
      - id: typos
        name: TypoCheck
        language: system
        entry: make --silent typos
        types: [lua, markdown, plain-text]
      - id: lintcommit
        name: LintCommit
        language: system
        entry: nvim
        args: ['--headless', '--noplugin', '-u', 'scripts/lintcommit.lua', '--']
        stages: ['commit-msg']
